### ISSUE TITLE
field lookup in returns deleted objects

### ISSUE THREAD

**Issue by zaifox** [makinacorpus/django-safedelete#101]
When using a queryset in a field lookup using "in", it also returns deleted objects. Example:

qs1 = Model1.objects.filter(Q(property=value1) | Q(property=value2))
qs2 = Model2.objects.filter(property__in=qs1)

Looking at the query executed when using qs1 in qs2 it does not exclude deleted objects.

Workaround is to transform it to list:
qs2 = Model2.objects.filter(value__in=list(qs1))

**Comment by Gagaro** [comment]
Are both `Model1` and `Model2` safedelete models ?

**Comment by aljp** [comment]
I've written a test that checks for this issue at https://github.com/aljp/django-safedelete/blob/test/queryset_in_lookup/safedelete/tests/test_lookups.py#L38 just to verify this error does occur.  I will look into a fix when I have time.

**Comment by muthuhari** [comment]
@zaifox did u fix this issue by using `list(qs1)` before passing it to `qs2` ?

**Comment by zaifox** [comment]
@muthuhari that's the workaround I used indeed.

**Comment by leestar123** [comment]
@zaifox  `    def __getattribute__(self, name):
        """Methods that do not return a QuerySet should call ``_filter_visibility`` first."""
        attr = object.__getattribute__(self, name)
        # These methods evaluate the queryset and therefore need to filter the
        # visiblity set.
        evaluation_methods = (
            '_fetch_all', 'count', 'exists', 'aggregate', 'update', '_update',
            'delete', 'undelete', 'iterator', 'first', 'last'
        )
        if hasattr(attr, '__call__') and name in evaluation_methods:
            def decorator(*args, **kwargs):
                self._filter_visibility()
                return attr(*args, **kwargs)
            return decorator
        return attr` 
why does not the evaluation_methods property contain 'filter'

**Comment by omaraltayyan** [comment]
sorry guys are there any plans to solve this, is it still the case that using this as a subquery doesn't apply the visibility filter?

**Comment by AndreasBackx** [comment]
> sorry guys are there any plans to solve this, is it still the case that using this as a subquery doesn't apply the visibility filter?

Could you create a PR that reproduces the problem in a failing test?

**Comment by omaraltayyan** [comment]
> > sorry guys are there any plans to solve this, is it still the case that using this as a subquery doesn't apply the visibility filter?
> 
> Could you create a PR that reproduces the problem in a failing test?

Sorry there's already a test case for this that's failing, also this issue is still open, and from checking the code it all seem to indicate that this is still a known issue right? Or is fully solved?

**Comment by AndreasBackx** [comment]
> Sorry there's already a test case for this that's failing, also this issue is still open, and from checking the code it all seem to indicate that this is still a known issue right? Or is fully solved?

I'm not sure I understand. There is no PR linked to this issue with a failing test in it. I am asking whether you could make a PR that adds a test that fails. Someone else could then have a look at fixing it in that same PR.

**Comment by Gagaro** [comment]
It's fixed in the last release, probably by https://github.com/makinacorpus/django-safedelete/commit/d54e2e4a357ce3ef8713eef4e47642260239c396

I added the test made by @aljp, thanks for that :+1: .
