### ISSUE TITLE
Duplicated line in _perform_unique_checks

### ISSUE THREAD

**Issue by twidi** [makinacorpus/django-safedelete#106]
As you can see, the first line of this extract from `_perform_unique_checks` serves no purpose and in fact make useless the `if` below. I guess it's a refactoring problem and this line should be removed.

https://github.com/makinacorpus/django-safedelete/blob/1663faaa22729a3f33f07933e4aecaf7578ffd48/safedelete/models.py#L190-L196

**Comment by AndreasBackx** [comment]
You're right. I made the mistake of not removing that line after working on it. (Unless it has some very weird side-effect, which I doubt.)
https://github.com/makinacorpus/django-safedelete/commit/4f4d29e1f1b465af6abc517cf827df2453a9d130#diff-8f659806f446f38ceb9b9ee89ae7bb86R182

**Comment by twidi** [comment]
I guess i can do it :)

**Comment by Gagaro** [comment]
We'll be waiting for you PR then :wink: .

**Comment by twidi** [comment]
See #107 ;)
