### ISSUE TITLE
highlight_deleted and russian letters

### ISSUE THREAD

**Issue by dvkovner** [makinacorpus/django-safedelete#109]
Hello! I've just tried to use your package and came across a problem. I want to use highlight_deleted in my model's admin. It works fine with latin letters, but doesn't work with cyrilic. For example, in the code below I'm getting this error: "'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)" cause my model's name field contains 'тест' value. Any suggestions?
```
class StockAdmin(SafeDeleteAdmin):
    """
    Акции
    """
    form = StockModelForm
    list_display = (highlight_deleted, 'name', 'date_start', 'date_end', 'type', 'amount_of_discount') + SafeDeleteAdmin.list_display
    list_filter = SafeDeleteAdmin.list_filter
    filter_horizontal = ('available_for_goods', 'categories')
```

**Comment by Gagaro** [comment]
Are you using python 2?

Does it work with the following method (note the `u` before the string):

```python
def highlight_deleted(obj):
    """
        Display in red lines when object is deleted.
    """
    obj_str = conditional_escape(text_type(obj))
    if not getattr(obj, 'deleted', False):
        return obj_str
    else:
        return format_html(u'<span class="deleted">{0}</span>', obj_str)
```

**Comment by dvkovner** [comment]
Yea. Python 2.7.15.

**Comment by Gagaro** [comment]
0.5.1 has been released with a fix.
