### ISSUE TITLE
rename 'deleted' to 'deleted_on'

### ISSUE THREAD

**Issue by SarunasAzna** [makinacorpus/django-safedelete#110]
`deleted` field is a DateTimeField therefore I suggest to add `_on` to its name so it would be clear that it is DateTimeField. Now you could interpret it as BooleanField (it is BooleanField on version [0.3.x](https://github.com/makinacorpus/django-safedelete/blob/0.3.x/safedelete/models.py#L55))
Apparently there is no Django [convention](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/) for Date/DateTimeField so the suggestions is based with:
1. [Over frameworks conventions](https://stackoverflow.com/questions/3759524/django-naming-conventions-for-dates).
2. Zen of Python mantra - Explicit is better than implicit. (DateTime/Boolean confusion violates that)
3. Complicated app migrations (0.3x to 0.4.x and newer)

**Comment by Gagaro** [comment]
We should keep that in mind for the next major version. It would have make migrations less painful indeed.

**Comment by theY4Kman** [comment]
I love this! Since I'm looking to replace django-softdelete during an upgrade to Django 2.0, I might try my hand at this and submit a PR.

One suggestion, though: "deleted_at" vs "deleted_on", for `DateTimeField` vs `DateField`.

> Row 456 was deleted on January 23, 2017

> Row 456 was deleted at 8:37, January 23, 2017

**Comment by tombreit** [comment]
This feature seems to be already implemented and documented in the top level [README.rst:](https://github.com/makinacorpus/django-safedelete/blob/master/README.rst#configuration) and on [RTD](https://django-safedelete.readthedocs.io/en/latest/index.html?highlight=SAFE_DELETE_FIELD_NAME#configuration) via the setting ``SAFE_DELETE_FIELD_NAME``.  Mentioned also in #162 .

**Comment by Gagaro** [comment]
Indeed, it is now configurabled.
