### ISSUE TITLE
Avoiding recursive call in delete() method

### ISSUE THREAD

**Issue by vmparikh** [makinacorpus/django-safedelete#117]
I have a code that performs certain operations before or after delete() method. I want it to be executed only once. It works perfectly in case of `_safedelete_policy = SOFT_DELETE`.

When value of `_safe_delete_policy` is `SOFT_DELETE_CASCADE`, it calls the foo.delete() twice inspite of me calling it once. Please refer to the following code:
```
class Foo(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE
    bar = models.ForeignKey(Bar on_delete=models.CASCADE)

    def delete(self, **kwargs):
        # my code before delete comes here
        # It will be executed twice
        super(Foo, self).delete()

bar = Bar()
foo = Foo(bar=bar)
foo.delete()
```
On further digging, I found these lines in safedelete/models.py
```
       elif current_policy == SOFT_DELETE_CASCADE:
            # Soft-delete on related objects before
            for related in related_objects(self):
                if is_safedelete_cls(related.__class__):
                    related.delete(force_policy=SOFT_DELETE, **kwargs)
            # soft-delete the object
            self.delete(force_policy=SOFT_DELETE, **kwargs)
```
Last line in above excerpt makes the second call. `self.delete()` here is equivalent to `foo.delete()` and hence can we avoid a recursive call?

**Comment by AndreasBackx** [comment]
If you want to execute some code before deletion, be it a soft or hard deletion, you can use the signals [`pre_softdelete`](https://django-safedelete.readthedocs.io/en/latest/signals.html), [`post_softdelete`](https://django-safedelete.readthedocs.io/en/latest/signals.html), and Django's own [`pre_delete`](https://docs.djangoproject.com/en/2.1/ref/signals/#pre-delete) and [`post_delete`](https://docs.djangoproject.com/en/2.1/ref/signals/#post-delete). Using these signals also applies to QuerySets.

**Comment by ngala** [comment]
Hi, thanks for the response. @vmparikh and I are working on the same issue.

We have a use-case where we can enforce policy during runtime based on user settings stored in the database. For example, if the admin wants to delete an object, he should be able to hard delete it. While users with a lower level of privileges shall not be allowed to hard delete the object.

Signals are relevant only after delete policy is fixed. Hence, I wanted to create another function that will call delete() method. But that leads to refactoring of codes everywhere and it is not intuitive either. Hence, we felt the need to raise an issue for the same.

**Comment by AndreasBackx** [comment]
Okay, valid issue. Perhaps we should move the contents from `delete` to `_delete` so recursive calls do not cause issues like that? Then we could also look at other methods that can use this and add a test case that tests whether it's only called once?

**Comment by ngala** [comment]
Yes, that solution would solve the issue we have.

**Comment by RmaxTwice** [comment]
Hi @Gagaro, you can close this issue, it was already addressed and fixed in https://github.com/makinacorpus/django-safedelete/commit/5a59e61c3a1d52b6719eb3522f8f082c43451119

**Comment by Gagaro** [comment]
Thanks for the heads-up :+1: .
