### ISSUE TITLE
Can this be make to work with Django auth.User model?

### ISSUE THREAD

**Issue by shiveshsky** [makinacorpus/django-safedelete#125]
I want to safe delete my Django auth User model.
Can this be made to work with that as currently it gets deleted from the database.

**Comment by Gagaro** [comment]
You can if you use your own user model. See https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#substituting-a-custom-user-model on how to do that.

**Comment by Singh-Sg** [comment]
I did that thing 
like this

class User(SafeDeleteModel, AbstractBaseUser, PermissionsMixin):
    _safedelete_policy = SOFT_DELETE

Please correct me if i'm doing something wrongs

**Comment by Gagaro** [comment]
Yes it should be like that. Do you have an issue with soft deletion of the user model?

**Comment by Singh-Sg** [comment]
Yes, that setup not working.
After deleting all object showing in query User.objects.all().

Please suggest me what is wrong.

On the package can we get dummy example where we can apply safe delete in user table

**Comment by Gagaro** [comment]
You probably need to make your own manager inheriting from both safedelete manager and user manager.

```python
class CustomUserManager(SafeDeleteManager, UserManager):
    pass


class CustomUser(SafeDeleteModel, AbstractBaseUser, PermissionsMixin):
    _safedelete_policy = SOFT_DELETE
    objects = CustomUserManager()
```
