### ISSUE TITLE
Support for Django 3

### ISSUE THREAD

**Issue by androane** [makinacorpus/django-safedelete#132]
Any plans to support Django 3? Currently I'm getting
```
TypeError: on_delete must be callable.
```
when using `on_delete=SOFT_DELETE_CASCADE`

**Comment by Gagaro** [comment]
Please read the documentation on how to use safedelete, it is currently tested and working with Django 3.0 on travis.

**Comment by androane** [comment]
@Gagaro don't think the use case I mentioned is covered. Nothing in the docs about this.

**Comment by Gagaro** [comment]
softdelete is not configured using the `on_delete` parameter. You need to set the `_safedelete_policy` attribute on the model.

**Comment by mkoistinen** [comment]
I think maybe the confusion comes from the fact that the lastest RTD documentation says:
![image](https://user-images.githubusercontent.com/615759/80390579-98d98000-887a-11ea-8567-a5ff53da903e.png)

**Comment by Gagaro** [comment]
I'm not sure to understand what you are trying to tell me?
