### ISSUE TITLE
undelete_selected() always reports SUCCESS even if it wasn't

### ISSUE THREAD

**Issue by mkoistinen** [makinacorpus/django-safedelete#137]
The `undelete_selected` admin action always reports SUCCESS even when the operation wasn't.

There are 2 reasons for this:
1. There's no logic for measuring success;
2. The construct `django.VERSION[1] <= 4` -- probably intended for versions 1.0...1.4 -- now prevents Django versions 2.0...2.4 and 3.0...3.4 from using the default INFO level.

PR incoming =)

**Comment by Gagaro** [comment]
Released in 0.5.5, thanks for the report/PR.
