### ISSUE TITLE
Objects with custom `.save()` logic cannot be undeleted. 

### ISSUE THREAD

**Issue by doganmeh** [makinacorpus/django-safedelete#139]
`.delete()` calls `super().save()`:

https://github.com/makinacorpus/django-safedelete/blob/4faeec341924c422f38ac4e2e73e6b65b13dcc03/safedelete/models.py#L145

However, `.undelete()` calls `self.save()`:

https://github.com/makinacorpus/django-safedelete/blob/4faeec341924c422f38ac4e2e73e6b65b13dcc03/safedelete/models.py#L117

Why is that discrepancy?

We have a model with custom logic in `self.save()` which prevents objects from being updated in certain situations. They can be deleted, but cannot be undeleted.

**Comment by Gagaro** [comment]
Saving a deleted object will undelete it. So undelete actually just call save to undelete.

What's your issue? Do you call the super save in your own save ?

**Comment by doganmeh** [comment]
Hey @Gagaro thank you for the response. 

Yes, we do call super save in our code, but that is not the issue. The issue is this:

We have a model with custom logic in `self.save()` which prevents objects from being updated in certain situations. They can be deleted (because `delete` calls `super().save()`), but cannot be undeleted (because `undelete` calls `self.save()`). 

Why does the `delete` not  call `self.save()` just like `undelete`. Because the latter is the undo of the former, it makes more sense to me that they followed the same route.

**Comment by Gagaro** [comment]
It should call `self` with `keep_deleted=True`. You're welcome to start a PR.
