### ISSUE TITLE
 The providing_args argument is deprecated

### ISSUE THREAD

**Issue by rituraj123db** [makinacorpus/django-safedelete#149]
**RemovedInDjango40Warning**: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring. **post_undelete = ModelSignal(providing_args=["instance", "using"], use_caching=True)**

**The above issue occurred by the updated version of django==3.1.6**

**Comment by 06parv** [comment]
> **RemovedInDjango40Warning**: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring. **post_undelete = ModelSignal(providing_args=["instance", "using"], use_caching=True)**
> 
> **The above issue occurred by the updated version of django==3.1.6**

The same issue occurred in my case please fix .@Gagaro @gibaneido

**Comment by Rupam-idealittechno** [comment]
Facing the same issue.

**Comment by Gagaro** [comment]
fixed in 1.0.0.

**Comment by rituraj123db** [comment]
@Gagaro Thanks
