### ISSUE TITLE
Add option to have is_deleted flag

### ISSUE THREAD

**Issue by gonzaloamadio** [makinacorpus/django-safedelete#165]
Hi, I am working on a legacy code that besides having the `deleted_at` field, it also has a boolean field `is_deleted`. I know it is not an uncommon pattern.

Would you like the idea of adding a configurable (optional) setting to also add this boolean field? I think it basically will be adding turning it to True or False next to where you set `deleted=timezone.now()`

I mean, something like:

```
HAS_BOOLEAN_FIELD = getattr(settings, 'HAS_BOOLEAN_FIELD', 'has_boolean_field')
BOOLEAN_FIELD_NAME = getattr(settings, 'BOOLEAN_SAFE_DELETE_FIELD_NAME', 'is_deleted')
```

Best regards!

**Comment by Gagaro** [comment]
Hi,
I'm not really fond of adding backward compatible code. Your best bet is probably to have your own model / manager which either annotate your boolean fields or add the field itself + the logic behind it.
