### ISSUE TITLE
Documentation website is not up to date

### ISSUE THREAD

**Issue by johnlarusic** [makinacorpus/django-safedelete#182]
Hello! It looks like the documentation available at https://django-safedelete.readthedocs.io/en/latest/ has not been updated since v0.5.  I'm looking to use this package and would super appreciate the latest docs, thank you!

**Comment by Gagaro** [comment]
Thanks for the heads up, it should be good now. I'm not sure why the webhook was removed, and there was a build error with the 4.0 version of Django (it's not pinned in setup.py), so only master should be available right now.
