### ISSUE TITLE
Documentation incomplete for unique constraints

### ISSUE THREAD

**Issue by bjudson** [makinacorpus/django-safedelete#194]
It appears that there's a missing code snippet in this section of the docs that would explain how to handle unique constraints:

> Because unique constraints are set at the database level, set unique=True on a field will also check uniqueness against soft deleted objects. This can lead to confusion as the soft deleted objects are not visible by the user. This can be solved by setting a partial unique constraint that will only check uniqueness on non-deleted objects:

https://github.com/makinacorpus/django-safedelete/blob/master/docs/models.rst#fields-uniqueness

I assume what we'd want here is something like:

```
class Meta:
    constraints = [
        models.UniqueConstraint(
            fields=["sku"],
            name="unique_sku",
            condition=Q(deleted_at=None),
        )
    ]
```

**Comment by Gagaro** [comment]
The code was actually in the rst but was not rendered because of a typo.

Thanks for the report :+1: .
