### ISSUE TITLE
Issues with new deleted_by_cascade field

### ISSUE THREAD

**Issue by torin-givemomentum** [makinacorpus/django-safedelete#206]
Hello, I recently updated to version 1.2 of django-safedelete, and quickly ran into two significant issues with the new deleted_by_cascade field.

The first issue is in the implementation of [related_objects](https://github.com/makinacorpus/django-safedelete/blob/c659ccf2b35cf32d6cddb57d8dec21fdbe7b1d52/safedelete/utils.py#L22). This method fails to handle the case where the object has no deleted_by_cascade field (because it's been disabled by setting it to None in the model definition). I think the problem is that the getattr call doesn't provide a default value, so if the model doesn't have that field it will raise an AttributeError. This bug is triggered if you undelete an object with SOFT_DELETE_CASCADE but its related objects have deleted_by_cascade disabled.

The second issue is that by adding a new required field to our models, the new version is by default incompatible with anything besides Django writing to our database. This is because Django adds default values on the application side, not in the database (as described [here](https://medium.com/botify-labs/django-and-its-default-values-c21a13cff9f) and various other places). So, simply by upgrading the django-safedelete version, any other processes writing to our database will start failing, as they are not providing the required deleted_by_cascade and the database doesn't provide a default value. I'm not sure if you would consider this a bug, but I suggest you consider making the field nullable, or having it disabled by default so that users aren't hit with unexpected bugs when upgrading versions of the library.

**Comment by Gagaro** [comment]
Fix released in 1.2.1

**Comment by torin-givemomentum** [comment]
> It actually poses no problem for a soft delete model with the field set to None (`getattr` will return None, this is unit tested). However, it will cause an issue for related models which are not soft delete ones. I'll add a fix and release in 1.2.1.

Awesome, you are of course correct, it's related non-soft delete models that are affected. Thanks for the quick fix!

> Indeed I wouldn't consider that a bug, and making it nullable wouldn't make much sense in the general use case. You have a specific use case outside of the scope of django-safedelete. My advice would be to overwrite the DELETED_BY_CASCADE field on your impacted models to set it nullable or to add a RunSQL in your migrations to set the default value.

My argument would be that adding a new required field into users' existing models constitutes a breaking API change (for the reasons I mentioned), so if it were up to me I would either have the feature default to disabled, or introduce it with a new major version in order to comply with [semantic versioning](https://semver.org/).

Of course, it's your project, so it's ultimately your decision.
