### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by roniemartinez** [makinacorpus/django-safedelete#212]
**After update from 1.1.2 to 1.2.2**

When calling delete() on related objects (`company.product_set.all().delete()`), the following error is thrown.

```
    def delete(self, force_policy=None):
        """Overrides bulk delete behaviour.
        .. note::
            The current implementation loses performance on bulk deletes in order
            to safely delete objects according to the deletion policies set.
        .. seealso::
            :py:func:`safedelete.models.SafeDeleteModel.delete`
        """
        assert self.query.can_filter(), "Cannot use 'limit' or 'offset' with delete."
        deleted_counter = Counter()
        # TODO: Replace this by bulk update if we can
        for obj in self.all():
>           _, delete_response = obj.delete(force_policy=force_policy)
E           TypeError: cannot unpack non-iterable NoneType object
```

**Comment by Gagaro** [comment]
Did you overwrite `delete` in your models?

`delete()` should return the same things than `Model.delete()` in 1.2.

**Comment by roniemartinez** [comment]
@Gagaro It's because in 1.2, the signature was changed. On prior versions (1.1 and below), this just return `None` (return not required)

![image](https://user-images.githubusercontent.com/2573537/173592998-bc5ae55a-2452-4d42-ad11-b48030f82238.png)

**Comment by roniemartinez** [comment]
Changeset: https://github.com/makinacorpus/django-safedelete/compare/1.1.2...1.2.2

For us, this is a breaking change because our models' `delete()` was implemented based on older versions of safedelete.
