### ISSUE TITLE
Django 4.2 support

### ISSUE THREAD

**Issue by sarahboyce** [makinacorpus/django-safedelete#223]
Hello hello :wave: thank you for this package

Been testing the [Django 4.2 alpha release](https://www.djangoproject.com/weblog/2023/jan/17/django-42-alpha-1-released/) against our project and it contains a [this change](https://github.com/django/django/commit/0701bb8e1f1771b36cdde45602ad377007e372b3) which is breaking [soft_delete_cascade_policy_action](https://github.com/makinacorpus/django-safedelete/blob/1e8c8baec6fac10274dc56ff3e6d81f32ab962cd/safedelete/models.py#L213) here:

```
        # update fields (SET, SET_DEFAULT or SET_NULL)
        for model, instances_for_fieldvalues in collector.field_updates.items():
>           for (field, value), instances in instances_for_fieldvalues.items():
E           AttributeError: 'list' object has no attribute 'items'
```

As this section appears to be copied from Django, the solution can probably also be [copied from what changed](https://github.com/django/django/commit/0701bb8e1f1771b36cdde45602ad377007e372b3) with some handling for different versions of Django.

When I get some time I will try to raise a PR but happy for anyone else to also take a look

**Comment by Gagaro** [comment]
Hello, thanks for the report :+1: .

Feel free to open a PR indeed, I'll gladly review / merge it.
