### ISSUE TITLE
deleted_objects is not documented anywhere

### ISSUE THREAD

**Issue by cristianrat** [makinacorpus/django-safedelete#226]
My issue is I need to email some users after the deletion of an object. But by the time my celery email jobs process, that object is already deleted, but I still need to access it.
Took me a while to find that I can do `MyModel.deleted_objects .get(pk=123)`
I can't remember where I found it, somewhere in code or something, but not in the documentation.
Or if it is there, I couldn't find it.
Or am I using this wrong?

**Comment by Gagaro** [comment]
It is documented there: https://django-safedelete.readthedocs.io/en/latest/models.html

If you feel like improving the documentation, feel free to do so and open a PR :+1: .

**Comment by cristianrat** [comment]
hmmm
guess I just didn't find it, or didn't search for the right keywords
thanks for pointing it out
