### ISSUE TITLE
If using django-simple-history, is this needed?

### ISSUE THREAD

**Issue by mustafa0x** [makinacorpus/django-safedelete#238]
Strictly speaking, safedelete is a subset of [simple-history](https://django-simple-history.readthedocs.io/en/latest/), is that correct?

So if I'm using simple-history I shouldn't need safedelete, right?

**Comment by Gagaro** [comment]
Yes you probably don't need it.

**Comment by mustafa0x** [comment]
Thanks @Gagaro!
