### ISSUE TITLE
How to use no-delete?

### ISSUE THREAD

**Issue by barseghyanartur** [makinacorpus/django-safedelete#37]
As advertised in the docs:

You can choose what happens when you delete an object :
1. it can be masked from your database (soft delete)
2. it can be normally deleted (hard delete)
3. it can be hard-deleted, but if its deletion would delete other objects, it will only be masked
4. it can be never deleted or masked from your database (no delete, use with caution)

I could not find option 4. Could you please clarify, how to implement no-delete with  `django-safedelete`?

Thanks!

**Comment by Gagaro** [comment]
You need to set the policy as NO_DELETE.
