### ISSUE TITLE
Cascade on Soft Delete

### ISSUE THREAD

**Issue by ish-vasa** [makinacorpus/django-safedelete#48]
Does this library support cascading soft deletes?

**Comment by Gagaro** [comment]
No, it only soft delete the one object you're deleting.

One of the idea is to be able to access foreign key even when they are "deleted".

You will have to do your own cascade.

**Comment by alanjds** [comment]
Is it acceptable if someone issue a PR implementing soft deletes on cascading instances?

**Comment by Gagaro** [comment]
As long as it's configurable (and not by default) and tested, I don't see any issue with that.

Maybe take a look at the 0.4.x branch before, I think I'll release it at the same time. I still need some feedback on it but I've been waiting for quite some time now.

**Comment by alanjds** [comment]
Nice. My comrade @gibaneido just issue this PR: https://github.com/makinacorpus/django-safedelete/pull/49

After this got accepted and merged, we can issue another PR over 0.4.x . It is the plan for now. If you need us to change the plan, just say, ok?

Thanks.

**Comment by Gagaro** [comment]
This is perfect, thanks :+1: .

**Comment by Gagaro** [comment]
I just released the 0.3.4. I'll let you do a PR for the 0.4.x branch, I'll release it afterward.

**Comment by Gagaro** [comment]
Done in c004473a7b497faace8d22df57faf528d5bacc74
