### ISSUE TITLE
test with django 1.10 and master

### ISSUE THREAD

**Issue by thenewguy** [makinacorpus/django-safedelete#54]
I was looking for a mixin that handles the edge cases I am encountering attempting to add masking to a model that I never want to be deleted.  This project seems to the what I am looking for.  I noticed the tests do not run on django 1.10 so I am raising this issue

**Comment by Gagaro** [comment]
Thanks for pointing that out. There is an issue with the 0.3.x branch I don't really have time to look into right now, but the [0.4.x](https://github.com/makinacorpus/django-safedelete/tree/0.4.x) branch works juste fine.

**Comment by Gagaro** [comment]
the 0.3.x branch will only have security fixes from now on. Move on to the 0.4.x one if you need Django 1.10 compatibility.
