### ISSUE TITLE
Separate tests

### ISSUE THREAD

**Issue by AndreasBackx** [makinacorpus/django-safedelete#57]
Tests like `SimpleTest.test_hard_delete_nocascade` only rely on 2 models of which 1 had a ForeignKey to the other. Because there are other models in the mix, that can mess up the tests which caused bug #56. Tests should be put in a subfolder and multiple files that each test a specific policy for example. It would weed out some perhaps future bugs that come with too tightly coupled tests.

**Comment by Gagaro** [comment]
If you make a PR I'll gladly merge it.

**Comment by AndreasBackx** [comment]
Alright, I'll add the refactoring of tests to #56. I'll notify you when I've finished.

**Comment by AndreasBackx** [comment]
I think all of it is now in #56.
