### ISSUE TITLE
Document how to migrate project using <0.4 to >= 0.4

### ISSUE THREAD

**Issue by hvdklauw** [makinacorpus/django-safedelete#61]
The change from boolean to datetime is a good one, but I think some documentation on how to handle the migration is really needed. 
PostgreSQL can't simply convert booleans to datetimes (some others might convert the int 1 to timestamp 1, not sure).

The correct way to go about this would be some manually crafted migrations:

1. Add a datetime column named `new_delete`
2. Fill the `new_delete` column based on the `delete` column (False = None, True = timezone.now())
3. Rename the `deleted` column to `old_deleted`
4. Rename the `new_deleted` to `deleted`
5. Also have the backwards migrations that do it the other way around.
6. At least 2 releases/deployments later (or how ever many rollbacks you want to be able to do) add a migration to remove the `old_deleted` column.

By at least documenting this you give people some guide on how to handle version upgrade without automatically marking all soft delete items as deleted (deleted_isnull=True doesn't match True nor False)

**Comment by Gagaro** [comment]
We discussed it in #55. I don't have time right now but I will definitively add some documentation about how to migrate later.

If someone is willing to do it before then, don't hesitate to do a PR.

**Comment by hvdklauw** [comment]
Did some more thinking about this.

Just renaming the columns is not going to work for anything with more then one frontend (unless you are willing to take some downtime).

You need to be able to put the new code on one frontend, run the migrations and still keep the old code working with the database.
It would have been better if the deleted column was renamed to `deleted_at` then it could have just been added (it's nullable, so old code keeps working) and after a while you could delete the old column.

**Comment by BeOleg** [comment]
Yup this is indeed missing

**Comment by hvdklauw** [comment]
This is a way to do it if you don't care about backwards compatibility or running multiple version of your code against the same database.

If you for instance want to update one frontend while keeping the old running this is not for you.



```python
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_deleted(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Model = apps.get_model('app', 'Model')
    for obj in Model.objects.using(db_alias).all():
        if obj.deleted:
            obj.deleted_at = obj.modified
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RunPython(migrate_deleted, migrations.RunPython.noop),
        migrations.RemoveField('Model', 'deleted'),
        migrations.RenameField(
            model_name='model',
            old_name='deleted_at',
            new_name='deleted',
        ),
    ]
```
