### ISSUE TITLE
safedelete fails to cascade properly with inheritance

### ISSUE THREAD

**Issue by wli** [makinacorpus/django-safedelete#68]
Somewhat related to https://github.com/makinacorpus/django-safedelete/issues/55

While figuring out how to add a db index to help with query performance (I know it was added in https://github.com/makinacorpus/django-safedelete/pull/67, but only for the 0.3.x branch), I decided to subclass the SafeDeleteMixin.

```
# Override safedelete mixin to enable db index.
class CustomSafeDeleteModel(SafeDeleteMixin):
    deleted = models.DateTimeField(editable=False, null=True, db_index=True)

    class Meta:
        abstract = True
```

The culprit appears to be that it only checks the first-level of `__bases__` to see if a model is a safedelete model: https://github.com/makinacorpus/django-safedelete/blob/6a20488785d4ac335d96031204064c53a25127e5/safedelete/models.py#L10

While my current issue can be solved in other ways, this does prevent django abstract model inheritance from working properly. It only manifests itself when setting the `_safedelete_policy` to `safedelete.models.SOFT_DELETE_CASCADE`, so it's pretty subtle.

For anyone looking for a quick short-term hack around this, you can do this so that `is_safedelete` works properly:

```
# Override safedelete mixin to enable db index.
class CustomSafeDeleteMixin(object):
    deleted = models.DateTimeField(editable=False, null=True, db_index=True)

    class Meta:
        abstract = True

class MyModel(SafeDeleteMixin, CustomSafeDeleteMixin):
   # ...
```

**Comment by Gagaro** [comment]
That's the way to go if you want to customize the `deleted` field (something which was not possible in 0.3.x and one of the reason why I wanted to get rid of factories).

Thanks for the report. I'm not sure to understand your workaround though. Does your `MyModel` model have the issue?

Or even better, could you make a PR with a test failing because of this issue?

**Comment by wli** [comment]
@Gagaro made a test for it that demonstrates the issue: https://github.com/makinacorpus/django-safedelete/pull/69

**Comment by wli** [comment]
Closing this, since #69 fixes this issue.
