### ISSUE TITLE
0.4.0 pypi release missing static directory

### ISSUE THREAD

**Issue by ciarancourtney** [makinacorpus/django-safedelete#75]
Download tarball from https://pypi.python.org/pypi/django-safedelete/0.4.0 and notice admin.css is missing

**Comment by ciarancourtney** [comment]
Also documentation doesn't mention adding safedelete to INSTALLED_APPS, which is required for collectstatic to work

**Comment by Gagaro** [comment]
Thanks for the report, the manifest isn't up to date. I'll update that asap (along with the doc).

**Comment by Gagaro** [comment]
0.4.1 has been released. Thanks again :+1: .
