### ISSUE TITLE
QuerySet first() method gives Cannot filter a query once a slice has been taken. 

### ISSUE THREAD

**Issue by glemmaPaul** [makinacorpus/django-safedelete#76]
Hey guys!

It seems that this code change gave me an issue, as following:
```
User.objects.filter(email="paul@email.nl").first()
```
Gives me:
```
File "/Users/pauloostenrijk/webprojects/app/app/users/import_export/resources.py", line 57, in before_import
user = User.objects.all().filter(email=row['email']).first()
File "/Users/pauloostenrijk/.virtualenvs/app/lib/python2.7/site-packages/django/db/models/query.py", line 550, in first
objects = list((self if self.ordered else self.order_by('pk'))[:1])
File "/Users/pauloostenrijk/.virtualenvs/app/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __iter__
self._fetch_all()
File "/Users/pauloostenrijk/.virtualenvs/app/lib/python2.7/site-packages/safedelete/queryset.py", line 121, in decorator
self._filter_visibility()
File "/Users/pauloostenrijk/.virtualenvs/app/lib/python2.7/site-packages/safedelete/queryset.py", line 98, in _filter_visibility
"Cannot filter a query once a slice has been taken."
AssertionError: Cannot filter a query once a slice has been taken.
```

Here are some implementation details:
```
from safedelete.managers import SafeDeleteManager

class UserManager(BaseUserManager, SafeDeleteManager):
```

```
@python_2_unicode_compatible
class User(SafeDeleteModel, AbstractBaseUser, TimeStampedUUIDModel, PermissionsMixin):
    objects = UserManager()
```

Version: 0.4.1

**Comment by dublinus** [comment]
This is happening to me as well, but it's happening for pretty much most of my queries. I'm not sure if it's conflicting with some other library, but even something as simple as:

    Item.objects.all()

results in an `AssertionError: Cannot filter a query once a slice has been taken`. I'm not sure what could be causing this.

**Comment by Gagaro** [comment]
Does it work with the PR #77 ?

**Comment by ciarancourtney** [comment]
@Gagaro I was getting this error for only some models in Django 1.11, error disappeared when I used PR #77

**Comment by AndreasBackx** [comment]
@ciarancourtney we're just waiting for a reply from @glemmaPaul and a follow-up commit and squash so it can be merged.

**Comment by ciarancourtney** [comment]
Actually I'm still getting this error with the latest PR for many of my test cases, mostly any test that gets an a instance like:

    MyModel.objects.all()[0]

will give a stacktrace:
```

  File "/opt/master/venv/lib/python3.6/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
  File "/opt/master/venv/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/opt/master/venv/lib/python3.6/site-packages/safedelete/queryset.py", line 125, in decorator
    self._filter_visibility()
  File "/opt/master/venv/lib/python3.6/site-packages/safedelete/queryset.py", line 100, in _filter_visibility
    "Cannot filter a query once a slice has been taken."
AssertionError: Cannot filter a query once a slice has been taken.
```

The admin changelist pages that were failing before are fine with the latest PR though

**Comment by ciarancourtney** [comment]
Replacing all .all()[0] querysets with .first() resolved my test failures. My codebase was originally written in Django 1.3, so I guess before first() was introduced in Django 1.6, it was acceptable to iterate querysets by index?

**Comment by AndreasBackx** [comment]
@ciarancourtney I was just thinking of that edge case. We should add tests for those as well.

**Comment by ewen** [comment]
I get this error using the Django REST Framework JSON API Pagination alongside safedelete, I guess it takes a slice at the pagination page size. Tested it against PR #77 but still fails.

I think it performs the slice here https://github.com/django/django/blob/master/django/core/paginator.py#L57 as it looks to be using the `django.core.paginator`.

**Comment by AndreasBackx** [comment]
@ewen we are aware of the issue and it'll get fixed in #77 as well.

**Comment by glemmaPaul** [comment]
@AndreasBackx this might be something we can solve by adding our functionality on the `iterator()` func, this is getting called when these slices happen.

**Comment by AndreasBackx** [comment]
@glemmaPaul would adding `'iterator'` to the `evaluation_methods` not do the job then?

**Comment by dublinus** [comment]
Any news on this? I'm still experiencing this bug.

**Comment by AndreasBackx** [comment]
@dublinus See #77

**Comment by dublinus** [comment]
@AndreasBackx I swear I tried this before and it didn't work. But it does now, thanks.

Is this PR going to be merged?

**Comment by Gagaro** [comment]
0.4.2 has been released with the fix.

**Comment by dublinus** [comment]
Love this library, thanks guys.

**Comment by zee93** [comment]
I get the same error with `earliest`, and `latest` queries. Can someone reopen -needs permission-this issue, or should I create a new one?
@glemmaPaul @Gagaro

**Comment by Gagaro** [comment]
Thanks for the report, I fixed it in master but I don't have the time to do a release right now. It will be for next week now.

**Comment by glemmaPaul** [comment]
Thanks @Gagaro for the catch up on this, appreciate it a lot!

**Comment by Gagaro** [comment]
0.4.4 has been released

**Comment by deepti62** [comment]
jnkjlnkjnbj
