### ISSUE TITLE
allow_tags deprecated in Django 2.0

### ISSUE THREAD

**Issue by ciarancourtney** [makinacorpus/django-safedelete#78]
Warning below appears in Django 1.9+

    RemovedInDjango20Warning: Deprecated allow_tags attribute used on field <function highlight_deleted at 0x7f32cd9ef9d8>. Use django.utils.html.format_html(), format_html_join(), or django.utils.safestring.mark_safe() instead.

I think you just need to wrap the html [here ](https://github.com/makinacorpus/django-safedelete/blob/master/safedelete/admin.py#L24)with format_html() instead

**Comment by ciarancourtney** [comment]
I'll try PRing this myself, do you have any contributing guidelines?

**Comment by AndreasBackx** [comment]
We should have some simple contributing guidelines. 🤔

**Comment by Gagaro** [comment]
These should be as simple as:

* Write tests
* Write a line in CHANGES

**Comment by AndreasBackx** [comment]
@Gagaro could we add some flake8 formatting tests to tox perhaps alongside with isort checks?

**Comment by Gagaro** [comment]
There is some: https://github.com/makinacorpus/django-safedelete/blob/master/tox.ini#L23

And in travis: https://github.com/makinacorpus/django-safedelete/blob/master/.travis.yml#L32-L34
