### ISSUE TITLE
Deletion of object is immediately reversed by save() method

### ISSUE THREAD

**Issue by jackappleby** [makinacorpus/django-safedelete#86]
Using, for example, the SOFT_DELETE policy, I'm finding that an object is correctly set with `self.deleted = timezone.now()`(https://github.com/makinacorpus/django-safedelete/blob/master/safedelete/models.py#L137). But then in the `save()` function, it is immediately undeleted. This is because `keep_deleted`  [is defaulted to False](https://github.com/makinacorpus/django-safedelete/blob/master/safedelete/models.py#L74), which results in [the deleted field being set to None](https://github.com/makinacorpus/django-safedelete/blob/master/safedelete/models.py#L95). The object is then saved as if the soft delete never occurred. For extra info, if I momentarily set the arg `keep_deleted` to True in the package save method, everything works.

Any clues as to what I'm getting wrong here would be much appreciated :)

**Comment by AndreasBackx** [comment]
This is the default behaviour. It might be interesting to allow for this to be changed with a constant as well. The current workaround is to overwrite `save()` yourself and pass `keep_delete=True`.

**Comment by jackappleby** [comment]
I see, thanks a lot. Perhaps just a note in the docs would be useful? For noobs like me it seems a strange default - but I'm sure it has it's reasons :)
