### ISSUE TITLE
Is there a way to forcefully delete in admin mode ?

### ISSUE THREAD

**Issue by mmohdnowfal** [makinacorpus/django-safedelete#88]

**Comment by Gagaro** [comment]
No, you have to do it in code. If it is a one use need, you can use `manage.py shell`.

**Comment by anuj9196** [comment]
I need this feature. In order to hard delete, I need to SSH to the server console and then execute the commands. A developer can do this but a manager with no knowledge of server handling can not do this.

**Comment by anuj9196** [comment]
A workaround for those who need.

Add a action to the admin using
```
class MyModelAdmin(SafeDeleteAdmin):
     ...
     
    actions = list(SafeDeleteAdmin.actions) + ['hard_delete_deleted_records']

    def hard_delete_deleted_records(self, request, queryset):
        data = queryset.all(
            force_visibility=DELETED_ONLY_VISIBLE
        )
        length = len(data)
        data.delete(force_policy=HARD_DELETE)
        self.message_user(request, '%s records deleted.' % length)

    hard_delete_deleted_records.short_description = 'Hard delete deleted records'
```

You can use `By Deleted` filter to get only deleted objects and select all objects in the list.
