### ISSUE TITLE
Django>=2.0 support

### ISSUE THREAD

**Issue by Euphorbium** [makinacorpus/django-safedelete#89]
Is there a plan to support the new django versions?

**Comment by Gagaro** [comment]
Hi,

I would have time to do that only if I work on a project which would require it. Which won't be the case before a long time.

I'd gladly review and merge a PR doing it though.

**Comment by Gagaro** [comment]
I added the 2.0 testing in travis: https://travis-ci.org/makinacorpus/django-safedelete

If it is just an issue with the import, I'll fix it and release it.

**Comment by Gagaro** [comment]
But I'd have to fix #90 first.

**Comment by ds-ac** [comment]
I have updated the test-cases: https://github.com/makinacorpus/django-safedelete/pull/93 seems to be working fine with Django 2.0

**Comment by Gagaro** [comment]
The tests are green with Django 2.0 (thanks @ds-ac !). If you still have issues, you can open a new issue, or even better, a PR with a failing test.

**Comment by Gagaro** [comment]
0.4.5 has been released with the support for Django 2.0

**Comment by Euphorbium** [comment]
Could update the docs and mention that this in fact does support django 2?

**Comment by Gagaro** [comment]
Yes, thanks for the heads up.
