### ISSUE TITLE
queryset method union returns deleted objects

### ISSUE THREAD

**Issue by zaifox** [makinacorpus/django-safedelete#97]
When I do the union of two querysets I get deleted objects back:
qs1.union(qs2)

Each individual query does not give the deleted object back. This is on a model set with SOFT_DELETE as safedelete_policy

**Comment by yuekui** [comment]
Hi @Gagaro @zaifox I believe this has been fixed in #145 and #152

**Comment by Gagaro** [comment]
It should be fixed by @yuekui PRs. Please reopen this issue if you still have the problem.
