### ISSUE TITLE
update_or_create() with unique contraint raises error

### ISSUE THREAD

**Issue by GitRon** [makinacorpus/django-safedelete#98]
Hi guys,

Case: SoftDeleteModel with a unique constraint on a field (not the regular id).

When I use MyModel.objects.update_or_create(my_unique_field=42, defaults={foo="bar"}) and the object is already softdeleted, I get an error: "Duplicate entry '42' for key 'my_unique_field' (#266)"

I wrote a custom manger to solve the issue, you've got a pull request.

I added a function testing if we need to do this depending if the model has a unique constraint defined. 

Maybe we need a case-handling for policies != soft_delete...

Best regards
Ron

**Comment by Gagaro** [comment]
0.5.0 has been released with the fix.

**Comment by GitRon** [comment]
Nice! Thanks!
